name: NoWitherBossbar
main: Rice.Chen.NoWitherBossbar.NoWitherBossbar
api-version: 1.20
folia-supported: true
version: 1.1

commands:
  nowitherbossbar:
    description: NoWitherBossbar plugin commands
    usage: /nowitherbossbar <reload|list>
    aliases: [nwb]
    permission: nowitherbossbar.admin
    permission-message: §cYou don't have permission to use this command!

permissions:
  nowitherbossbar.admin:
    description: Allows access to all NoWitherBossbar commands
    default: op